version: '3.7'

services:

  universalmediaserver:

    image: universalmediaserver/ums
    container_name: ums
    network_mode: host
    environment:
      - UMS_PROFILE=/profile
      
    volumes:
      - /media/profile:/profile
      - /media/media:/media:ro

    restart: always

#volumes:
#  profile:

#  media:
