version: '2.4'

volumes:
  serviio-config: 
    external: true
  serviio-start:
    external: true

services:
  serviio:
    image: cina/serviio:latest
    container_name: serviio
    volumes:
      - serviio-config:/config 
      - /tmp:/transcode 
      - /etc/localtime:/etc/localtime:ro 
      - /media:/media 
      - /mnt/storage/media:/mnt/storage/media 
    network_mode: 'host'
    mem_limit: 1gb
    environment:
      - 'SERVIIO_OPTS=-Dserviio.cdsAnonymousAccess=true'
      - 'PGID=996' 
      - 'PUID=997' 
    restart: unless-stopped
